use_frameworks!

platform :ios, '11.0'

target 'LXExtension_Example' do
  pod 'LXExtension', :path => '../'

  target 'LXExtension_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
